server:
  port: 8082

spring:
  application:
    name: ServiceB
  config:
    import: "optional:configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: health,info
