spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true

# --- peer1 ---
---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:peer1

# --- peer2 ---
---
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id:${spring.application.name}:peer2
