server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:transferdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

client:
  checkingBaseUrl: http://localhost:8081
  savingBaseUrl: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
