server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: stock
          uri: lb://stock-service
          predicates:
            - Path=/api/stock/**
          filters:
            - stripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: htpp://localhost:8761/eureka/, http://localhost:8762/eureka/
