spring:
  application:
    name: stock-service

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,beans,httpexchanges,loggers"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Optional: include trace/span IDs in log lines
logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%mdc{traceId:-},spanId=%mdc{spanId:-}]"

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true




